import type { DesignTrendResponse } from "@/types/design-trends"

/**
 * Fallback data for design trends when API fails
 */
export const designTrendsFallbackData: DesignTrendResponse = {
  trends: [
    {
      id: "1",
      title: "Neomorphism in UI Design",
      description:
        "Exploring the evolution of skeuomorphism into a modern, subtle design approach that combines flat design with realistic elements.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "UI/UX",
      date: "June 15, 2023",
      author: "Alex Morgan",
      readTime: "5 min read",
      tags: ["UI Design", "Neomorphism", "Trends"],
      url: "/design-trends/ui-ux/neomorphism",
      featured: true,
    },
    {
      id: "2",
      title: "Dark Mode Everywhere",
      description:
        "How dark mode has evolved from a developer preference to a mainstream design choice across platforms and applications.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "UI/UX",
      date: "May 28, 2023",
      author: "Jamie Wilson",
      readTime: "4 min read",
      tags: ["Dark Mode", "UI Design", "Accessibility"],
      url: "/design-trends/ui-ux/dark-mode",
    },
    {
      id: "3",
      title: "Glassmorphism: Transparency & Blur",
      description:
        "The rise of glass-like interfaces with transparency, blur effects and subtle borders that create depth and hierarchy.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Visual Design",
      date: "April 10, 2023",
      author: "Taylor Reed",
      readTime: "6 min read",
      tags: ["Glassmorphism", "Visual Design", "Transparency"],
      url: "/design-trends/visual-design/glassmorphism",
    },
    {
      id: "4",
      title: "3D Elements in Web Design",
      description:
        "How 3D elements are being integrated into web interfaces to create immersive and engaging user experiences.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Web Design",
      date: "March 22, 2023",
      author: "Jordan Lee",
      readTime: "7 min read",
      tags: ["3D Design", "Web Design", "Interaction"],
      url: "/design-trends/web-design/3d-elements",
    },
    {
      id: "5",
      title: "Micro-interactions: Small Details, Big Impact",
      description:
        "The importance of subtle animations and feedback in creating intuitive and delightful user experiences.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Interaction Design",
      date: "February 15, 2023",
      author: "Casey Kim",
      readTime: "5 min read",
      tags: ["Micro-interactions", "Animation", "UX"],
      url: "/design-trends/interaction-design/micro-interactions",
    },
    {
      id: "6",
      title: "Minimalist Typography Trends",
      description: "Exploring how clean, bold typography is becoming a central design element in modern interfaces.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Typography",
      date: "January 30, 2023",
      author: "Riley Johnson",
      readTime: "4 min read",
      tags: ["Typography", "Minimalism", "Trends"],
      url: "/design-trends/typography/minimalist-trends",
    },
    {
      id: "7",
      title: "Asymmetric Layouts",
      description: "Breaking the grid with intentional asymmetry to create dynamic, engaging layouts that stand out.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Layout Design",
      date: "January 12, 2023",
      author: "Morgan Smith",
      readTime: "6 min read",
      tags: ["Layout", "Asymmetry", "Web Design"],
      url: "/design-trends/layout-design/asymmetric-layouts",
    },
    {
      id: "8",
      title: "Immersive Color Gradients",
      description:
        "How vibrant, multi-toned gradients are being used to create depth and visual interest in digital interfaces.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Color Theory",
      date: "December 5, 2022",
      author: "Sam Rivera",
      readTime: "5 min read",
      tags: ["Color", "Gradients", "Visual Design"],
      url: "/design-trends/color-theory/gradients",
    },
    {
      id: "9",
      title: "Voice User Interfaces",
      description:
        "The evolution of voice UI and how designers are creating experiences for conversation-based interactions.",
      image: "https://img.freepik.com/premium-photo/natural-background-sunset_28898-1.jpg?semt=ais_hybrid&w=740",
      category: "Emerging Tech",
      date: "November 18, 2022",
      author: "Alex Morgan",
      readTime: "8 min read",
      tags: ["Voice UI", "Emerging Tech", "Interaction"],
      url: "/design-trends/emerging-tech/voice-interfaces",
    },
  ],
  categories: [
    { name: "All", slug: "all", count: 9 },
    { name: "UI/UX", slug: "ui-ux", count: 2 },
    { name: "Visual Design", slug: "visual-design", count: 1 },
    { name: "Web Design", slug: "web-design", count: 1 },
    { name: "Interaction Design", slug: "interaction-design", count: 1 },
    { name: "Typography", slug: "typography", count: 1 },
    { name: "Layout Design", slug: "layout-design", count: 1 },
    { name: "Color Theory", slug: "color-theory", count: 1 },
    { name: "Emerging Tech", slug: "emerging-tech", count: 1 },
  ],
  hasMore: false,
  total: 9,
}
